/**
 * EDUNEXIS - Export Module (Excel via SheetJS CDN)
 */

/**
 * Export receipts to Excel-compatible XLSX
 */
async function exportToExcel(receipts, filename) {
    if (typeof XLSX === 'undefined') {
        throw new Error('Excel library not loaded. Please check your internet connection.');
    }

    const rows = receipts.map(r => ({
        'Receipt No.': r.receiptNo,
        'Receipt Date': r.date,
        'Receipt Time': r.time,
        'Institute Name': r.instituteName,
        'Student Name': r.studentName,
        'Father\'s Name': r.fatherName,
        'Mother\'s Name': r.motherName,
        'Enrollment No.': r.enrollmentNo,
        'Admission No.': r.admissionNo,
        'Roll No.': r.rollNo,
        'Course': r.course,
        'Year/Semester': r.yearSemester,
        'Session': r.session,
        'Mobile': r.mobile,
        'Email': r.email,
        'Address': r.address,
        'Payment Mode': r.paymentMode,
        'Transaction ID': r.transactionId,
        'Bank/Cheque No.': r.bankChequeNo,
        'Payment Date': r.paymentDate,
        'Payment Status': r.paymentStatus,
        'Subtotal': r.subtotal,
        'Discount': r.discount,
        'Late Fee': r.lateFee,
        'Other Charges': r.otherCharges,
        'Grand Total': r.grandTotal,
        'Amount Paid': r.amountPaid,
        'Balance': r.balance,
        'Amount in Words': r.amountInWords,
        'Status': r.status,
        'Generated By': r.generatedBy,
        'Notes': r.notes || ''
    }));

    const ws = XLSX.utils.json_to_sheet(rows);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, 'Receipts');

    // Auto width
    const colWidths = Object.keys(rows[0] || {}).map(key => ({ wch: Math.max(key.length, 12) }));
    ws['!cols'] = colWidths;

    const fname = filename || `EDUNEXIS_Receipt_Data_${new Date().toISOString().slice(0, 10)}.xlsx`;
    XLSX.writeFile(wb, fname);

    return true;
}

/**
 * Export fee heads summary or custom
 */
async function exportCustom(data, sheetName, filename) {
    if (typeof XLSX === 'undefined') {
        throw new Error('Excel library not loaded.');
    }
    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, sheetName || 'Data');
    XLSX.writeFile(wb, filename || 'EDUNEXIS_Export.xlsx');
}

window.EDUNEXIS_EXPORT = {
    toExcel: exportToExcel,
    custom: exportCustom
};